services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "10000-10100:10000-10100/udp"
    env_file:
      - .env
    restart: unless-stopped
